### ISSUE TITLE
Messages de $cal et $jdr ne s'affichent pas dans le canal

### ISSUE THREAD

**Issue by younesbourakadi** [UnionRolistes/Bot_Planning_python#41]

**Comment by Fr-Dae** [comment]
ce n'est pas un bug mais un bot qui supprime automatiquement les commande pour ne laisser que la réponse

**Comment by Fr-Dae** [comment]
![Uploading Capture d’écran du 2023-08-31 15-40-52.png…]()

**Comment by Fr-Dae** [comment]
![Capture d’écran du 2023-08-31 15-40-52](https://github.com/UnionRolistes/Bot_Planning_python/assets/23202421/43d76380-5b7d-452e-8e12-5057d265b973)

**Comment by Fr-Dae** [comment]
si mais il s'affiche déjà
juste il de supprime directe

**Comment by younesbourakadi** [comment]
J'en avais parlé à mortifia pour $prez, et il a dit qu'il fallait qu'il affiche "Un lien a été envoyé dans vos messages privés pour accéder au calendrier du rôliste !"

**Comment by younesbourakadi** [comment]
Donc je remets $prez comme avant ? je laisse $jdr et $cal telles quelles ?

**Comment by Fr-Dae** [comment]
$prez présentation = Un lien a été envoyé dans vos messages privés pour vous présenter dignement !
$jdr fiche planning = Un lien a été envoyé dans vos messages privés pour créer un nouvel événement !
$cal calendier = Un lien a été envoyé dans vos messages privés pour accéder au calendrier du rôliste !

**Comment by younesbourakadi** [comment]
Donc il faut qu'il s'affiche, on est d'accord
